[package]
name = "neo4j"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
neo4rs = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
